apiVersion: v1
kind: Secret
metadata:
  name: innovatech-db-secrets
type: Opaque
data:
  # "Despachocontraseña" en Base64 es: RGVzcGFjaG9jb250cmFzZcOxYQ==
  mysql-password: RGVzcGFjaG9jb250cmFzZcOxYQ==