apiVersion: apps/v1
kind: Deployment
metadata:
  name: despachos-deployment
spec:
  replicas: 2
  selector:
    matchLabels:
      app: ms-despachos
  template:
    metadata:
      labels:
        app: ms-despachos
    spec:
      containers:
        - name: ms-despachos
          image: 137700910242.dkr.ecr.us-east-1.amazonaws.com/innovatech-despachos
          ports:
            - containerPort: 8081
          resources:
            requests:
              cpu: "100m"
              memory: "256Mi"
            limits:
              cpu: "200m"
              memory: "512Mi"
          env:
            - name: SPRING_DATASOURCE_URL
              valueFrom:
                secretKeyRef:
                  name: innovatech-db-secrets
                  key: url
            - name: SPRING_DATASOURCE_USERNAME
              valueFrom:
                secretKeyRef:
                  name: innovatech-db-secrets
                  key: username
            - name: SPRING_DATASOURCE_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: innovatech-db-secrets
                  key: mysql-password
---
apiVersion: v1
kind: Service
metadata:
  name: despachos-service
spec:
  ports:
    - port: 8081
      targetPort: 8081
  selector:
    app: ms-despachos
  type: ClusterIP