name: Deploy Innovatech Backend to EKS

on:
  push:
    branches:
      - deploy

env:
  AWS_REGION: us-east-1
  EKS_CLUSTER_NAME: devopseks
  ECR_REGISTRY: 522965979796.dkr.ecr.us-east-1.amazonaws.com

jobs:
  build-and-deploy:
    name: Build, Push & Deploy to EKS
    runs-on: ubuntu-latest
    steps:
      - name: 1. Checkout del código
        uses: actions/checkout@v3

      - name: 2. Configurar credenciales AWS
        uses: aws-actions/configure-aws-credentials@v2
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-session-token: ${{ secrets.AWS_SESSION_TOKEN }}
          aws-region: ${{ env.AWS_REGION }}

      - name: 3. Login en Amazon ECR
        id: login-ecr
        uses: aws-actions/amazon-ecr-login@v1

      - name: 4. Construir y Subir MS Ventas
        run: |
          cd back-Ventas_SpringBoot/
          docker build -t ${{ env.ECR_REGISTRY }}/innovatech-ventas:${{ github.sha }} -t ${{ env.ECR_REGISTRY }}/innovatech-ventas:latest -f Dockerfile .
          docker push ${{ env.ECR_REGISTRY }}/innovatech-ventas:${{ github.sha }}
          docker push ${{ env.ECR_REGISTRY }}/innovatech-ventas:latest

      - name: 5. Construir y Subir MS Despachos
        run: |
          cd back-Despachos_SpringBoot/Springboot-API-REST-DESPACHO
          docker build -t ${{ env.ECR_REGISTRY }}/innovatech-despachos:${{ github.sha }} -t ${{ env.ECR_REGISTRY }}/innovatech-despachos:latest -f Dockerfile .
          docker push ${{ env.ECR_REGISTRY }}/innovatech-despachos:${{ github.sha }}
          docker push ${{ env.ECR_REGISTRY }}/innovatech-despachos:latest

      - name: 6. Conectar GitHub Actions al Clúster EKS
        run: |
          aws eks update-kubeconfig --name ${{ env.EKS_CLUSTER_NAME }} --region ${{ env.AWS_REGION }}

      - name: 7. Desplegar Infraestructura en Kubernetes
        run: |
          # Aplica todos los archivos dentro de la carpeta k8s
          kubectl apply -f ./k8s/
          
          # Fuerza a los pods a reiniciar para asegurar que descarguen la última imagen que acabamos de subir
          kubectl rollout restart deployment/ventas-deployment
          kubectl rollout restart deployment/despachos-deployment